export function personIndex() {
  return Promise.resolve({
    data: {
      people: peopleMap
    }
  })
}

export function personShow(id) {
  // TODO: make this a Promise
  return Promise.resolve({
    data: {
      person: peopleMap[id]
    }
  })
}

const peopleMap = {
  '00-01': {
    id: '00-01',
    firstName: 'Lawrence',
    middleName: '',
    lastName: 'Heatherington',
    maidenName: '',
    prefName: 'Lawrence',
    sex: 'male',
    birthYear: 1891,
    birthMonth: 8,
    birthDay: 16,
    birthCity: 'Lurgan',
    birthState: 'Armagh',
    birthCountry: 'Northern Ireland',
    deathYear: 1964,
    deathMonth: 1,
    deathDay: 27,
    deathCity: 'Massena',
    deathState: 'NY',
    deathCountry: 'USA',
    generation: 0,
    photo: 'https://i.imgur.com/fl4BbV3.jpg',
  },
  '00-02': {
    id: '00-02',
    firstName: 'Clara',
    middleName: 'Estella',
    lastName: 'Heatherington',
    maidenName: 'Risley',
    prefName: 'Clara',
    sex: 'female',
    birthYear: 1889,
    birthMonth: 6,
    birthDay: 20,
    birthCity: 'Richfield Springs',
    birthState: 'NY',
    birthCountry: 'USA',
    deathYear: 1952,
    deathMonth: 10,
    deathDay: 7,
    deathCity: 'Russel',
    deathState: 'NY',
    deathCountry: 'USA',
    generation: 0,
    photo: 'https://i.imgur.com/g0HTU1m.jpg',
  },
  '01-01': {
    id: '01-01',
    firstName: 'Lawrence',
    middleName: 'Risley',
    lastName: 'Heatherington',
    maidenName: '',
    prefName: 'Lawrence',
    sex: 'male',
    birthYear: 1913,
    birthMonth: 9,
    birthDay: 24,
    birthCity: 'Richfield Springs',
    birthState: 'NY',
    birthCountry: 'USA',
    deathYear: 1983,
    deathMonth: 11,
    deathDay: 16,
    deathCity: 'Amherst',
    deathState: 'NY',
    deathCountry: 'USA',
    generation: 1,
    photo: 'https://i.imgur.com/IHjedHF.jpg',
  },
  '01-02': {
    id: '01-02',
    firstName: 'Ruth',
    middleName: 'Jean',
    lastName: 'Nichols',
    maidenName: 'Heatherington',
    prefName: 'Jean',
    sex: 'female',
    birthYear: 1915,
    birthMonth: 5,
    birthDay: 2,
    birthCity: 'Ohio',
    birthState: 'NY',
    birthCountry: 'USA',
    deathYear: 1994,
    deathMonth: 9,
    deathDay: 4,
    deathCity: 'Massena',
    deathState: 'NY',
    deathCountry: 'USA',
    generation: 1,
    photo: 'https://i.imgur.com/cjOrv6b.jpg',
  },
  '01-03': {
    id: '01-03',
    firstName: 'Marion',
    middleName: 'Louine',
    lastName: 'Pernice',
    maidenName: 'Heatherington',
    prefName: 'Louine',
    sex: 'female',
    birthYear: 1918,
    birthMonth: 10,
    birthDay: 10,
    birthCity: 'Wellesley Island',
    birthState: 'NY',
    birthCountry: 'USA',
    deathYear: 1984,
    deathMonth: 6,
    deathDay: 23,
    deathCity: 'Massena',
    deathState: 'NY',
    deathCountry: 'USA',
    generation: 1,
    photo: 'https://i.imgur.com/fgoCeLI.jpg',
  },
  '01-04': {
    id: '01-04',
    firstName: 'Elsie',
    middleName: 'Elizabeth',
    lastName: 'Buck',
    maidenName: 'Heatherington',
    prefName: 'Elsie',
    sex: 'female',
    birthYear: 1920,
    birthMonth: 5,
    birthDay: 5,
    birthCity: 'Wellesley Island',
    birthState: 'NY',
    birthCountry: 'USA',
    deathYear: 1976,
    deathMonth: 12,
    deathDay: 30,
    deathCity: 'Massena',
    deathState: 'NY',
    deathCountry: 'USA',
    generation: 1,
    photo: 'https://i.imgur.com/3yu0vzJ.jpg',
  },
  '01-05': {
    id: '01-05',
    firstName: 'Francis',
    middleName: 'Viola',
    lastName: 'Myers',
    maidenName: 'Heatherington',
    prefName: 'Viola',
    sex: 'female',
    birthYear: 1922,
    birthMonth: 3,
    birthDay: 14,
    birthCity: 'Wellesley Island',
    birthState: 'NY',
    birthCountry: 'USA',
    deathYear: 1978,
    deathMonth: 1,
    deathDay: 10,
    deathCity: 'Clermont',
    deathState: 'FL',
    deathCountry: 'USA',
    generation: 1,
    photo: 'https://i.imgur.com/aZgrRZL.jpg',
  },
  '01-06': {
    id: '01-06',
    firstName: 'Hazel',
    middleName: 'Margaret',
    lastName: 'Fox',
    maidenName: 'Heatherington',
    prefName: 'Hazel',
    sex: 'female',
    birthYear: 1924,
    birthMonth: 1,
    birthDay: 3,
    birthCity: 'Natural Bridge',
    birthState: 'NY',
    birthCountry: 'USA',
    deathYear: 2018,
    deathMonth: 9,
    deathDay: 17,
    deathCity: 'Stoughton',
    deathState: 'MA',
    deathCountry: 'USA',
    generation: 1,
    photo: 'https://i.imgur.com/HLY8jmr.jpg',
  },
  '01-07': {
    id: '01-07',
    firstName: 'Murial',
    middleName: 'Mae',
    lastName: 'Bicknell',
    maidenName: 'Heatherington',
    prefName: 'Murial',
    sex: 'female',
    birthYear: 1926,
    birthMonth: 1,
    birthDay: 26,
    birthCity: 'Natural Bridge',
    birthState: 'NY',
    birthCountry: 'USA',
    deathYear: 1953,
    deathMonth: 9,
    deathDay: 15,
    deathCity: 'Canton',
    deathState: 'NY',
    deathCountry: 'USA',
    generation: 1,
    photo: 'https://i.imgur.com/0KE3oZe.jpg',
  }
}

export default (
  personIndex,
  personShow
)