export const person1 = {
  firstName: 'Lawrence',
  middleName: '',
  lastName: 'Heatherington',
  maidenName: '',
  sex: 'male',
  birthYear: 1891,
  birthMonth: 8,
  birthDay: 16,
  birthCity: 'Lurgan',
  birthState: 'Armagh',
  birthCountry: 'Northern Ireland',
  deathYear: 1964,
  deathMonth: 1,
  deathDay: 27,
  deathCity: 'Massena',
  deathState: 'NY',
  deathCountry: 'USA',
  generation: 0,
}

export const person2 = {
  firstName: 'Clara',
  middleName: 'Estella',
  lastName: 'Heatherington',
  maidenName: 'Risley',
  sex: 'female',
  birthYear: 1889,
  birthMonth: 6,
  birthDay: 20,
  birthCity: 'Richfield Springs',
  birthState: 'NY',
  birthCountry: 'USA',
  deathYear: 1952,
  deathMonth: 10,
  deathDay: 7,
  deathCity: 'Russel',
  deathState: 'NY',
  deathCountry: 'USA',
  generation: 0,
}
